# Generated by Django 6.0.6 on 2026-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corpusdocument_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusdocument',
            name='slug',
        ),
    ]
