# Generated by Django 6.0.6 on 2026-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_corpusdocument_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkhistory',
            name='stats',
            field=models.TextField(blank=True, default=''),
        ),
    ]
